"""Added users table

Revision ID: 9157d00e307a
Revises: aa23e4bc5ce9
Create Date: 2022-01-19 21:29:35.237154

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9157d00e307a'
down_revision = 'aa23e4bc5ce9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscription',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('city_id', sa.String(), nullable=False),
    sa.Column('state_id', sa.String(), nullable=True),
    sa.Column('country_id', sa.String(), nullable=True),
    sa.Column('conditions', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_subscription_id'), 'subscription', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subscription_id'), table_name='subscription')
    op.drop_table('subscription')
    # ### end Alembic commands ###
